/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USB_UART.h"
#include "USB_UART_SPI_UART.h"
#include "USB_UART_PINS.h"
#include "USB_UART_SPI_UART_PVT.h"
#include "USB_UART_PVT.h"
#include "USB_UART_BOOT.h"
#include "Pin_Blue.h"
#include "Pin_Blue_aliases.h"
#include "Input_1_Int.h"
#include "Input_0_Int.h"
#include "Input_Pin_1.h"
#include "Input_Pin_1_aliases.h"
#include "Input_Pin_0.h"
#include "Input_Pin_0_aliases.h"
#include "Output_Pin_0.h"
#include "Output_Pin_0_aliases.h"
#include "Output_Pin_1.h"
#include "Output_Pin_1_aliases.h"
#include "USB_UART_SCBCLK.h"
#include "USB_UART_tx.h"
#include "USB_UART_tx_aliases.h"
#include "USB_UART_rx.h"
#include "USB_UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

